### ISSUE TITLE
Fatal error when testing parse_test.js

### ISSUE THREAD

**Issue by nassan** [leftshifters/excel-parser#28]
When I run the unit tests, tests fail in the parse_test.js file with a "Fatal error: Cannot read property 'length' of undefined" error. Not really sure what to do, I am new at this, this was the shell output:

PS C:\Users\...\node_modules\excel-parser> grunt nodeunit
Running "nodeunit:tests" (nodeunit) task
Testing parse_test.jsFatal error: Cannot read property 'length' of undefined

**Comment by sthawali** [comment]
@nassan Make sure you have installed all the dependencies listed here,
https://github.com/leftshifters/excel-parser/wiki/Python-library-installation-steps
Also, I notice that you are using windows, check relative file path and its permissions.

**Comment by nassan** [comment]
Thank you so much!
